name: Build & Code Quality

on:
  push:
    branches:
      - release
      - master
    tags:
      - v**
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  build-and-code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@vv4.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20.x'

      - name: Instal Dependencies
        run: npm run fresh-install

      - name: Run Unit Tests
        run: npm run build && npm run build-storybook

      - name: Check Syntax (ES Lint)
        run: npm run lint
