name: Build & Code Quality

on:
  push:
    branches:
      - release
      - master
    tags:
      - v**
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  build-and-code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: '20.x'

      - name: Instal Dependencies
        run: yarn run fresh-install

      - name: Run Unit Tests
        run: yarn run test

      - name: Build
        run: yarn run build && yarn run build-storybook

      - name: Check Syntax (ES Lint)
        run: yarn run lint
