name: Deploy StoryBook

on:
  push:
    branches:
      - master

jobs:
  deploy-sb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@vv4.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '20.x'

      - name: Instal Dependencies
        run: npm ci

      - name: Build StoryBook
        run: npm run build-storybook

      - name: Deploy StoryBook
        run: npm run gh:deploy-storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
