name: Deploy StoryBook

on:
  push:
    branches:
      - master

jobs:
  deploy-sb:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.3.0

      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: '22.x'

      - name: Instal Dependencies
        run: yarn install

      - name: Build StoryBook
        run: yarn run build-storybook

      - name: Deploy StoryBook
        run: yarn run gh:deploy-storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
